nameSuffix: -fi-jyvaskyla
resources:
- ../../base

commonLabels:
  app.kubernetes.io/instance: gtfsrt-vp-poller-fi-jyvaskyla
  app: gtfsrt-vp-poller-fi-jyvaskyla

secretGenerator:
  - name: gtfsrt-vp-poller
    literals:
    - http-username=foo
    - http-password=bar
    - pulsar-oauth2-key=whatever
    options:
      disableNameSuffixHash: true

