apiVersion: v1
kind: Secret
metadata:
    name: gtfsrt-vp-poller-fi-lahti
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: gtfsrt-vp-poller-fi-lahti
data:
    http-username: ENC[AES256_GCM,data:wsYe7NiLEOs=,iv:HzJTmZUXHcgyppXMJt7qqDdB+M4a6ewB6nDdgaWBcWQ=,tag:TfRrZjIyWxVAcG4fLmHtpg==,type:str]
    http-password: ENC[AES256_GCM,data:ZaPxZJzN4lA3/rYa,iv:hwZ4SfA4IBD3sjFwnICFjSyMLsudMhZ1hBmjEPMn4Ys=,tag:aSi/p2lGI6xcjaiHbjuHpw==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-05-22T07:24:28Z"
          enc: CiQAUhREB2cgFnmRDlnTIlRELxRJueNauWKzu7F/eKAxHFsG0VQSSQD4ANZeuJTOummPKVc15JvBNtnbh2veLajLIFLasUoGN4onLnlgZ4JmdQTqhJof2DN+ylfkNRHAB6NWnOxkrESaGtC8xHPwIfo=
    lastmodified: "2026-05-22T07:24:29Z"
    mac: ENC[AES256_GCM,data:5gDEUBHXtu3frNgp35enV0Oc4RU07OZDJqecsfjFVNBnQLE0YGfTjTZ9qp0xYSKFxaZ9HfSnOCZXRYCxlT3iAU92Q5gB299wO84xlyqJt2h3D+Tf1gXi/iUp0ivx9DjOV7suGn/N8fNOTxzIY2FTZ+to2yZd6eoeDfw5xepXg3E=,iv:q+pX31aKV0F+Bq+aGhS7i71GnZJkW2x9+gahH+p3zLg=,tag:geo4xKoDzii3zdyR1fdL1g==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
