namespace: qa
resources:
  - ../../base

configMapGenerator:
  - name: journey-matcher
    behavior: merge
    literals:
      - 'FEED_MAP=[["persistent://apc-staging/source/gtfsrt-vp-fi-kuopio",["fi:kuopio","221","Europe/Helsinki"]],["persistent://apc-staging/source/gtfsrt-vp-fi-jyvaskyla",["fi:jyvaskyla","209","Europe/Helsinki"]]]'
      - 'PINO_LOG_LEVEL=info'
      - "PULSAR_APC_CONSUMER_TOPICS_PATTERN=persistent://apc-staging/deduplicated/mqtt-apc-from-vehicle"
      - "PULSAR_GTFSRT_CONSUMER_TOPICS_PATTERN=persistent://apc-staging/source/gtfsrt-vp-.*"
      - "PULSAR_PRODUCER_TOPIC=persistent://apc-staging/aggregated/aggregated-apc-journey"

patches:
  - path: history-limit.yaml

generators:
  - ./ksops-secret-generator.yaml