namespace: qa
resources:
  - ../../base

configMapGenerator:
  - name: mqtt-deduplicator
    behavior: merge
    literals:
      - "PULSAR_CONSUMER_TOPICS_PATTERN=persistent://apc-staging/source/mqtt-apc-from-vehicle"
      - "PULSAR_PRODUCER_TOPIC=persistent://apc-staging/deduplicated/mqtt-apc-from-vehicle-deduplicated"
      - "PINO_LOG_LEVEL=info"

patches:
  - path: history-limit.yaml

generators:
  - ./ksops-secret-generator.yaml