resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: anonymizer

secretGenerator:
  - name: anonymizer
    literals:
      - pulsar-oauth2-key=whatever
    options:
      disableNameSuffixHash: true

configMapGenerator:
  - name: anonymizer
    literals:
      - >-
        AUTHORITY_MAP=[
          ["221","fi:kuopio"],
          ["209","fi:jyvaskyla"]
        ]
      - HEALTH_CHECK_PORT=8080
      - PINO_LOG_LEVEL=info
      - PULSAR_APC_SUBSCRIPTION=anonymizer-apc-sub
      - PULSAR_BLOCK_IF_QUEUE_FULL=true
      - PULSAR_COMPRESSION_TYPE=ZSTD
      - PULSAR_PROFILE_READER_NAME=anonymizer
      - PULSAR_OAUTH2_ISSUER_URL=https://auth.streamnative.cloud
      - PULSAR_OAUTH2_KEY_PATH=/secrets/pulsar-oauth2-key
      - PULSAR_TLS_VALIDATE_HOSTNAME=true
