apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-kuopio
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-kuopio
data:
    http-username: ENC[AES256_GCM,data:ONqYsAzM65o=,iv:CV1EO92Gv147G0OVitdflescMsaB8EQ3mJTd5uQwGgY=,tag:CKCVF85bgc7t9rK50mFZTA==,type:str]
    http-password: ENC[AES256_GCM,data:l+K5A+QpZ9d1j5nvyjaK5Q==,iv:Oj4tlQpsyInx4uo20ZwFeaT+SsW9ImNlrL3RnNE1jSI=,tag:E+tKLfHY9PZ6RqRgBgVqkQ==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:11:13Z"
          enc: CiQAQ7huFp5ZuMtSDkTdGzluimvVk9nurLuY7LhJ+v35klbcnCcSSQC//AyihuCfms0HsFt9vJWXPXguJ/w5kPU5LOO2xGLql5vRnJ7DvmqscrMPzyL/NJlaZ+FsKNKP9/tghQ5cmWGAk5bt7BKGQ84=
    lastmodified: "2026-05-22T07:22:24Z"
    mac: ENC[AES256_GCM,data:4/Fb6kaRfPJ1YG/egKFlYFtU85tPffHbM7RqzjpC7vSM50O1KWQqvWwEMEqPjj1gkzm1B9CP4Aa/p2eFZwgLVrGdcS7HfKUx3vxScL/T5zmjc+CYfnbRztA9YXJ9NxdYa3HQT0bLnUe6v2L58OmnEwSMfSd1aBYTdCSaIjJmhoU=,iv:2iYNp0T315jHwhjcHiXxZKKfyES+MmEBBBy6/6MUE+4=,tag:+HMPsYLFZDEKg8xKSQiixQ==,type:str]
    encrypted_regex: ^(data)$
    version: 3.7.3
