apiVersion: v1
kind: Secret
metadata:
    name: anonymizer
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: anonymizer
data:
    pulsar-oauth2-key: ENC[AES256_GCM,data:JN9y0FfEM6ouz8kw7OVrEif/mZol2ODTD0y2YGWl+cfbBypY0mZ132CCtCucflPAfclHkKAM8La2asjXS8fG/SI2Bst+7buFI73OkIJXmqFlrl8S/OA+Rv0l83pJLqIdrLatLy95b5QK04MQYrhj3L6zWnoaoP6WNu5wPrUdoF3drd/0NbjdU39F9xNdPrpoSozwZtHiKhGXS9rhHet2Nk0TGGewxvqII04jSlttAhIBK9Bw/fKpIAXe/Ec5uq/tJRQcmuL1y3IGo8Ywm5nvfw9UeGyZwIcyVsQYCa7kTDSCwhrO9/GjdxMmepcaqeUD3uzmA7ULTuaGLGWJFCk+S9Tr5v5v7att4vf6hj0uGPfMT4tRJpq1K1ctJDqcdlJ0OdJNfJ8+wUsndCh46Q2wylEJZ2z3oefqkXfetnA6Scjlc3c3Uqp8LR++DPsodehF3hvzsYCe1UZg4A6cLLW2UraP/b8G8kBC,iv:CIYdbx7JusTw7UPtXz1ewldWk1nq9LmHLPvUoiEzdnY=,tag:KZX6qW0ZhUmyloSWi6KG3Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-09-13T10:38:58Z"
          enc: CiQAUhREBx+9mnAPhGdWVsOxYbp2dknqI+f7kDX3eAVIpwsbu8QSSQD4ANZe3OLYk8q/l6mlf/TAICnhu4NPof3Lraj2q7UyJ/+87wmMU8F65mRRuDMZ7xPn5bL8Ciu5J8H/l9H/sk5ban/7NKd71Cg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-13T10:38:59Z"
    mac: ENC[AES256_GCM,data:MaueThRBTAK3WgsQ/TirI9qnds4KXOlDwwfaXYwyh2JwXV/W9Ig11ozaOcANQwacv5y7uZKQxx3P8Hqs7ngNem5wCqt7xoIEBt3vEkrpUij4ffHk2pty9NakyF+Zo5ZqQ1oPDha3Lu+xJ4LTOGAXpGgUtTX3EkgnKsHUgRPkaKI=,iv:6roU+/ASVgf8vmKtXr3nfctrc7PcKczq3bLQbfHeMkQ=,tag:S0HsQAo1LW5l9FO/ng32BQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.8.0-rc.1
