apiVersion: v1
kind: Secret
metadata:
    name: mqtt-pulsar-forwarder
    annotations:
      kustomize.config.k8s.io/behavior: replace
    labels:
      app.kubernetes.io/name: mqtt-pulsar-forwarder
data:
  mqtt-username: Zm9vCg==
  mqtt-password: Zm9vCg==
  pulsar-oauth2-key: eyJ0eXBlIjoic25fc2VydmljZV9hY2NvdW50IiwiY2xpZW50X2lkIjoidlJMUGxhZjZsSkpwb1FZNFk2ZDdtYzVydDhTMmtqYXYiLCJjbGllbnRfc2VjcmV0IjoiZ1E1YjBCdlM2VG9xLTc4c1E3U01LS09WNGlRWnhNU043UV8zSkJWTmxQUGM1cjRWNlZfREhBOWZkYjBwRW4wdSIsImNsaWVudF9lbWFpbCI6Im1xdHQtcHVsc2FyLWZvcndhcmRlckB3YWx0dGkuYXV0aC5zdHJlYW1uYXRpdmUuY2xvdWQiLCJpc3N1ZXJfdXJsIjoiaHR0cHM6Ly9hdXRoLnN0cmVhbW5hdGl2ZS5jbG91ZC8ifQ==
