apiVersion: v1
kind: Secret
metadata:
    name: mqtt-pulsar-forwarder-temp
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: mqtt-pulsar-forwarder-temp
data:
    mqtt-username: ENC[AES256_GCM,data:3Bs146W/Y0/tRIeS3d/4dY0PkdRHwQOIbfEQwYQxaXOC/zke/8rnqDdGtxU=,iv:xF0UTxb1jYfiTdjhCYNHBW2MrlRQ8kPYVsKpABdbQ3A=,tag:hhuC6z8G00OdDBIvLn5ikg==,type:str]
    mqtt-password: ENC[AES256_GCM,data:B7sR/FfWuQvbb+BHBWI80Q==,iv:zg39If3c29lUUgoSNnmvsqwSamq2I8ElBCWLZqJVgNQ=,tag:kTzJeaJI6SLNNEwtEg0e7A==,type:str]
    pulsar-oauth2-key: ENC[AES256_GCM,data:36d/9HxcL0cRmIaGsT8oaMDevkJEF4RXSCSQKb21awaYdujxyHI6qAY+n3yfu7vMa76jJefDWh/Us5s3R7K6PJKBUbcldhXh418Q0gT8br0DK0jr7ZyA1kQhxrsL0geaF6laJWcNENM3P4Ypi6s1pecR3qaQF6X5uPjjjHZpKKqbFFuMdTy9KqwxxArHVI9vpWDe/NCcArWYQbhpQlOIgmE4kQR0LTkRwZ7N7jJtpRpYhUYxWPDtHVqqefePYNxP2cgeeoYXSGO9jaBL6dn0pY+VLpgcJ9X103PB/k/UWZp8olZ/ymi5NQnjstfh7tDKsE+ehHq+DPjwZg6xcK6AgHPIb1/keLr6jH1vfhiOdo7ea29LeyP06/3GVUPlZqJWS8lJc+zVeMGqNHnUp6Zq3cvPe05o+ORwbkfokhplrMUL57mlxTpXHXPLoetEoAcLZZ9K15050J3k67fZ84sdkPo+jBZeZcYI,iv:+C+WQcEl0TtGBPM1Qm2jExc3JSAOA4v+sJBxBT/Xn7E=,tag:/B+P3NsEinAdwuoX15oMXA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-08-17T17:27:28Z"
          enc: CiQAUhREB0XAU3MWV6kSlxwzrCiYOEiqLsKUB7CuOk48yljcxycSSQD4ANZewE+g93e1R1c0MWb8tyrVPmI4sPC4jydqc/SXGvsVE/ixY6vpzJ69mPGDE/4pN70zt6LIuffUYiWVy6wxjNTPVfvKHF0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-17T17:27:28Z"
    mac: ENC[AES256_GCM,data:mJni6AJTlNDq6lju5quLvi/29V/cFyreS2YpylhQXhuOC4AniwbN4xZChMxwFQqqSpiIk/ciWLyS9MIom/7LLzNUErL0jGNlL8hR14AfFgUgWHrb84CGUVnclI1bfxmDDx6IJ/Vo9o8rVruqOtsDiT4ApPAn/W6mdvVzJHgBT64=,iv:IC0di1uy8mbEg7WlVoDhq030BVhCcChK1XTbxrUgHjg=,tag:TFh7LZ1jJ3GtCZkQRUn+Ug==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
