apiVersion: v1
kind: Secret
metadata:
    name: mqtt-pulsar-forwarder
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: mqtt-pulsar-forwarder
data:
    mqtt-username: ENC[AES256_GCM,data:oP9enSEUURop02PGnpk+9WToIQ141l1vo/VjiOOjqKsQh0EOW6fw3rmp2H0=,iv:WOxHuHmLaqochQS+z2B1jA7zXDgR063Qhctg/7E3I/s=,tag:uLqQ6TrQXQCyTPRNa2rS/Q==,type:str]
    mqtt-password: ENC[AES256_GCM,data:1sGEbAsDHqxHSYMWdMkPfOM9dBqesnck8SzBIw==,iv:W2edMp3OtYb24W2RP++b0jYkSnCr1f4Ig9wFY+jhFis=,tag:bPau4/GcAcg/m892usJS5g==,type:str]
    pulsar-oauth2-key: ENC[AES256_GCM,data:uO0bWxoIlJaH3ZI+/AxHKC3dYVZWSeutRPsRoGaCvswYzEhekRuuviGqA5JiGdH7lbAfvK7pA2Wk2Y9oDHlZ6KuVXubEtyo13Mvqijw0/fdPBIUBfClnbVlUb7QqceySf7VieIAenffyksr+rBtIEPzENITHRDdJJqSHgUz0BdjMmMKEGsKL2PQY6cV6KiUysNK+fDT8t6YH3ZzpKUmjUncBHqCXOC3brXSkQOW/Z2f7xDabjAM4VYfRXKoBp/c5zk0LPsd2BTxXMND8jv0fXTl+f51sOosGWTat59+7EQPMUawXLJfROP6uq5JZwaOU1JRCMBBETl/eB9efpqOsP5gvII6vnROluT3S2yuHA4tk4kJX/IElM0Ubc2AbHfOQUifmj+LlGB5WTOXeSULtTYXNfU0fbTNx/6ZJw5GACkM5B5qnHG+kdb5rUzVj5A==,iv:fzCVGsQ7YLdNiuVzk43nCBvOA0iLnMhTJWybsgv4NjA=,tag:J1YSKjfreJnQuz7HnouSgw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-08-14T18:10:27Z"
          enc: CiQAUhREB/Z4yErPuy/IN789KyYAA0LonNt7TKIlp2+kN5q3fCUSSQD4ANZeCQMOVCaxY54vQ3SZGwj16JzsqwDk8Jd0VLLxTwSj6NTaqrZ7gYE/wWx7uGs2nL/xDvHMLWVNQNu/qaHj1a6ajK3HPD8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-14T18:10:27Z"
    mac: ENC[AES256_GCM,data:95bkuKSeDF+xnIYl4j/4L57lXjOLPjTNJ+lgUAWeBZuSqDglbTeeUQGF60m8gZ30hVzrajSNtFJRcWSNuIQ2ZQZ6VwznqZlHX+SZxZDsK8v7FiI9Ow4Y4dNuULzzjJ6Jt3yeJ8w/4SvNuFzLa+ntDPWgC3cGiPogisvbGq2RyHE=,iv:3E7k1vbsbo95efxf+I3Mtky/M0FqdVQGR/F7HcSM/oQ=,tag:uJn7YcO262BfJUcnnpWX7A==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
