apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-jyvaskyla
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-jyvaskyla
data:
    http-username: ENC[AES256_GCM,data:VTCCxxtyz48=,iv:jmQH06MaLWueHvENU4mpPs4xbiq0hsGDggiFLTET1GU=,tag:svbrUJnVHvombl0LBm0L1Q==,type:str]
    http-password: ENC[AES256_GCM,data:y1+AVWNJgEoX0hlilBiFJQ==,iv:3/2MihR29o1Q273DypNscBAfpmdmOzGKTvS5RjFZI3I=,tag:49nAJCO69a80oAsKYbGQFQ==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-03T09:30:41Z"
          enc: CiQAUhREB8loKJqEEJQpC+0CR7nUbYTuSrShS8CYiKHDsNlqoDASSQD4ANZeYzPrOC+qaO1mlNqIZdm8RkbS3l3b0Ucvs0aRqCtSg6WoGBpWWQfMTad6OtTHhRjuHQbgeVpOjCPuIL7LOb24uEFD/x4=
    lastmodified: "2026-02-03T09:30:41Z"
    mac: ENC[AES256_GCM,data:SVMh6/7ViSK6/wQZYrohrCbH9ZwayBMWMA81ljzDqIhVyvJGKTprvQYOTkgLgoxU2k5JrrhKPZwbpcQGXGmXI9ONgUl+v9FqsOAY4ZAS/cJwqR3AE1rvd/6gaV9HwF/YI+UU8RAnmJt96AotgSimtOe9wpUhZdpTzsIEDEWWGys=,iv:YcPTBHN2fl3Gg8IL74fOc5sPybcfz0P7eNKoEaIfMR0=,tag:ZcLnkUZ8dEv/MXXH0ggRSA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
