apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-lahti
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-lahti
data:
    http-username: ENC[AES256_GCM,data:9U9o0PTSHpM=,iv:4SUC8mTR57YFQtIgw4LXnrF0p3cCCV8zw/OwXCckK9o=,tag:C3GYfgdNd0nYbqg9kZx0aA==,type:str]
    http-password: ENC[AES256_GCM,data:FGyQEfWzSReXe0eUMkzyWw==,iv:D2w5S7aZnMWGNpWgZrnEa/EjZP29T1cMBCK/00iSDVE=,tag:AZVTsrxQGx2qiEQDIs02zw==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-05-22T07:24:27Z"
          enc: CiQAhLiU4Wle7NnyDcggxIX6dAYNP5EtZ5nDJNnLtb+V1mnLJcgSSQDOezfyOxEcqVDJ0b6xr+l8zFvurV4axsN1Np7JGdlNYB3BGsVFYwrooageVN2CvAfFsCO7c9E+jnVxsHCYww0fhXZA1429Dwo=
    lastmodified: "2026-05-22T07:36:57Z"
    mac: ENC[AES256_GCM,data:967FtCHNF95fPnsdNmRwBNAZ4iP3Mnfp/moS72/1ETokOaOwy3pEC4vOlDAWMPmnD5AdtwwQ/ynvXbN0Ri0Nz1NBBlFeNYOB7GuocDpmSFyG9Rh4KbCkCCqpNAzT9wpMTDdlgS31Q4/VcIpMtATDW4yyhF7hOFx38wcj/hztmaE=,iv:rxZWy1I1P3rXFmShmVaUkFUj+Lz45pExjMWeHAmrMGI=,tag:pKl1ME4PzZ+ts7L3sJGm6A==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
