apiVersion: v1
kind: Secret
metadata:
    name: gtfsrt-vp-poller-fi-kuopio
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: gtfsrt-vp-poller-fi-kuopio
data:
    http-username: ENC[AES256_GCM,data:dLzDKwcbR1g=,iv:/IRp1Bkn3TOzBHK5RyS3NeDDKtpbEKwogriO68Ybsnc=,tag:zwRCDGpROXJLZx5Rab7FaQ==,type:str]
    http-password: ENC[AES256_GCM,data:KMHlMYHvxvR6Koyt,iv:JbkBYbinYv+ViuGWqQeUBFQQ2BCp5vmGcvXYZEbL/W8=,tag:k2by9MDDeWZ2CARvMOAG3Q==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:24:41Z"
          enc: CiQAUhREB0aYVP+eThd4Z0or7KmFvm9V711moyGGxlLXEI7+GhcSSQD4ANZeVlkoTENqqXNDxPNI9R3o4RZe5YyyDdzVxGE/Rg6Q7a3PvZl4UKkIBZH36o3iL6GXY2puzjPxsma621Ud692aPPJoJp0=
    lastmodified: "2026-05-22T07:22:27Z"
    mac: ENC[AES256_GCM,data:+qLlh8tFm1vQVeshqQ06Rqv5b7PweUKypy36ZRlMjMJfmYWReDEAUYxEqWbu0NOziIUeMi7dWpOjunR7FNwHoutjzJNQM81xbhiorF9Obgk3DO6cIgxibxfKwWFCkyv9DCytFIAuMxVzBopmFaSc2ACv4HjrK8NHSQJaVZdKNTg=,iv:+07D3yL5CC1/eNjNhq/LtfOhzjcTwzlpDJsy7D1s+JY=,tag:9R1Yxja1euONxMwJz25YHA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.7.3
