resources:
  - deployment.yaml

configMapGenerator:
  - name:  vehicle-registry-poller
    literals:
    - HEALTH_CHECK_PORT=8080
    #- HTTP_PASSWORD_PATH=TO_BE_FILLED_IN_OVERLAY
    - HTTP_REQUEST_TIMEOUT_IN_SECONDS=5
    # Poll every 6hrs
    - HTTP_SLEEP_DURATION_IN_SECONDS=21600
    - HTTP_URL=TO_BE_FILLED_IN_OVERLAY
    - HTTP_USER_AGENT=waltti-apc-http-pulsar-poller
    #- HTTP_USERNAME_PATH=TO_BE_FILLED_IN_OVERLAY
    - PINO_LOG_LEVEL=info
    - PULSAR_BLOCK_IF_QUEUE_FULL=true
    - PULSAR_COMPRESSION_TYPE=ZSTD
    - PULSAR_IS_URL_IN_MESSAGE_PROPERTIES=false
    - PULSAR_OAUTH2_ISSUER_URL=https://auth.streamnative.cloud
    - PULSAR_OAUTH2_KEY_PATH=/secrets/pulsar-oauth2-key
    - PULSAR_TLS_VALIDATE_HOSTNAME=true
    - PULSAR_TOPIC=TO_BE_FILLED_IN_OVERLAY
