apiVersion: v1
kind: Secret
metadata:
    name: http-pulsar-poller-fi-jyvaskyla-vp
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: http-pulsar-poller-fi-jyvaskyla-vp
data:
    http-username: ENC[AES256_GCM,data:B6Ahwi3mcPs=,iv:TwXIojt74NEQYYw+QtpNUCP+yvSc3jFx38ePzPluSco=,tag:kc+GxwSAwh/svs7kiEXZGw==,type:str]
    http-password: ENC[AES256_GCM,data:FsnsIqlYhtw=,iv:fH3xG9z8mDijTXwrWpXJdyfrf+bl+GZlOMLaVOhz+wU=,tag:ZsyVY9F1tAtuF4glhTBnrA==,type:str]
    pulsar-oauth2-key: ENC[AES256_GCM,data:kQUpQEb9eNvXNc85TGSq+lOCkl3HZtKqTFgA5pl4UXLcqOh7nv4BQCiXJItaRYijKUoipVRkl/ySH8OUyUIYKwutA1oCAoB3oBW25CCwuAv2sOen99EWX+cGb2RwozzVilqjKafMgugluxFjE4NMpD1g639t2zO+f9aSYizjgAfG6caFWT7TS4yBIFmahjdO2jdCboiDuNDCNFQ2eHe1Q+rpgX4t7H4P1JftggQzNEg0ZTlKt4Yc1EiObWI0SUDmsPnjWPc7Zw5zYWeauSt/TBiic85rYIgM3ZvSNIAuM+KVMfgODI7KsWvmn7aHRGeRS57pZEpRt8vDOwY3Rx2Lct4ZViFFIiD/FUFM6nnPPukiBBHgBgDb6Nxy8kaOkMBc/5DliTU4xGyS/uOwe/7WwaEY+v6I1x2oyjzYPkUYF6a9cinx8NphIW3XhS/I00dx9huBA2eRspK5Lh4rz79yyrIb+zev247Fuk/Gp9vnlhT2WjHn,iv:Mw+qeqAPZwdb7gVBjdTsAKKqrUO9rQGpi6LIueDa1oM=,tag:ic0RRJ1QJEcAkIkqRhur6Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-04-18T10:23:17Z"
          enc: CiQAQ7huFrQwfSoQ2ezFhWN2ixM9oLLFDhVczJmFLU/QDC3uKscSSQC//AyiXPIrCmOyB55M1k1HUAJZfnQcdCYoZcyThIJCpkTtJJVfi4xstKTt4kYXR7mSuhzBI68HLW/kWDSD245vQjPJb2UVOAo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-18T10:23:18Z"
    mac: ENC[AES256_GCM,data:MKXP5Q4okf1TqWWrKnD99JtoZTIXMVje1kZEcpGvQGPmh4mlc4GOG/3m4yQIPgy5XmmvWmRXLtTOWvuksdYpiiWllRHx6JAYg5mRhdjAG7MNvTBfg30uHJWwgnO8FJeEZkTWW7GzRiSTXwp3ZHDFz2aPcNCKDFpnVMBKh8E3eeM=,iv:8oKvc8bUXb83cNvQmZD8aw5r9A8/MSmigz/A0PLCeBw=,tag:yVqgenHLtrlpoH52Ai95cQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
