namespace: dev
#namePrefix: dev-
resources:
  - ../../base
  - namespace.yaml

configMapGenerator:
  - name: mqtt-pulsar-forwarder-config
    behavior: merge
    literals:
      - "MQTT_URL=mqtts://lively-cobalt-wasp.rmq5.cloudamqp.com"
      # For some reason the StreamNative certificate does not match the URI.
      - "PULSAR_TLS_VALIDATE_HOSTNAME=false"
      #- "PULSAR_TOPIC=persistent://apc-dev/source/mqtt-apc-from-vehicle"
      - "PULSAR_TOPIC=persistent:fooz"
generators:
  - ./ksops-secret-generator.yaml