namespace: dev
resources:
  - ../../base

configMapGenerator:
  - name: vehicle-registry-poller-fi-kuopio
    behavior: merge
    literals:
      - "HTTP_PASSWORD_PATH=/secrets/http-password"
      - "HTTP_URL=https://vilkkutestadmin.mattersoft.fi/externalapi/assets/allvehicles"
      - "HTTP_USERNAME_PATH=/secrets/http-username"
      - "PULSAR_TOPIC=persistent://apc-sandbox/source/vehicle-catalogue-fi-kuopio"
      - "PULSAR_OAUTH2_AUDIENCE=urn:sn:pulsar:waltti:alpha"
      - "PULSAR_SERVICE_URL=pulsar+ssl://sandbox.waltti.snio.cloud:6651"
patches:
  - path: history-limit.yaml

generators:
  - ./ksops-secret-generator.yaml