apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-lahti
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-lahti
data:
    http-username: ENC[AES256_GCM,data:xSiHR70Eroo=,iv:xf8qCSOIFNEtrZ+UB1fx+Cp08qROY5bsUs7pq6+EQ4s=,tag:0L5a/bMqmSfMFGbzhk4vqg==,type:str]
    http-password: ENC[AES256_GCM,data:VJJkntckr1v33ySbaIskTA==,iv:vk2Tjnrlr3LMGo4N90XHluRuQu8sKUBrP/2bS+ze2ac=,tag:Z0SYuiZy72ipOLMxq+wqXg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-05-22T07:24:26Z"
          enc: CiQAUhREByCl2kFzVqb+xCJgWyT+myKO0/iR9thGIcGA3QxziFQSSQD4ANZe2rYnYHKuy3A5frXqjjFuIdHZXVdVjC7csY+QeaRNQ/hwNdEguGkWy3R9FNRek7MlCmNGrm58YgfkOlFJOSUBqH9kg/o=
    lastmodified: "2026-05-22T07:36:56Z"
    mac: ENC[AES256_GCM,data:OC6W906kyS2omrXPLrlJlc6tyQxUPOGy7EAoZ0W7Eex6YdpqepnUT9kuKpezzqndZdW7CnjfovUqQWZWJs+N1cJYJ6006LRtjl1Wo1xbw9xsEtfkp29uov/7Ysf1HQO6gJ5pnIAvOJ6emyfxC90W3gV6IvZdgx/bZar+cIX5tFA=,iv:/t4orkr17z0Ou85tO8YNBGeDg2SQR695NoFXcumG4GY=,tag:N34R8pPIZJn8hHL4hsRKTA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
