apiVersion: v1
kind: Secret
metadata:
    name: mqtt-message-inspector
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: mqtt-message-inspector
type: Opaque
data:
    mqtt-username: ENC[AES256_GCM,data:mf9mdK1bjNeXzR1cCQzq2Q==,iv:aGw4BRTxH8V0lHb+hOFmO02RJRe3i+EAmHsow41HCpA=,tag:i2u/M1J9E46IDgBwDXvL/w==,type:str]
    mqtt-password: ENC[AES256_GCM,data:LG4C+T+S83XonF14wzwmHFKRsgvx0BIyu2O8wc+rQdCorxSAr5xa403buWFZSbR4tB1tsSrm/ucnNKi8,iv:022Ol9vaHr2ujwl8UOHe9mVwA1aFHQpBAFkJMJTVVyY=,tag:S/7UiMC84JH0/tyVdt4t9w==,type:str]
    http-username: ENC[AES256_GCM,data:v0HqJ2wpfMR886K/5Ex/xUVS6Z+6U8KK,iv:uZDAKcTgc1eNdcOExJxk1uok0/zgWxUvomo2BBH2kDY=,tag:+HXlyz6XnOwR7FX8yR3qew==,type:str]
    http-password: ENC[AES256_GCM,data:V8ZmtZX3Lp1uytrJ9EwylOfrcpRtBhHl8grLMvzp+vMzykv/FJ2ZUDTeg1E=,iv:F6kla4psObFHedvbE/zNgWeEd3wN7BoNbZDjoCySBNk=,tag:1kbgSpRwIaD5Dp+EROno7w==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-27T12:47:03Z"
          enc: CiQAhLiU4fYGMR1TfLTGlfcQpnLECArMKOhiccizFaX7c78s788SSQDOezfygyxFkqDdyuogX1N0Z4wSBHU7OZBH4FeP7NYTxV7oGyVIIKuc7/y18tBYUY/txPMylZ/rPcNINXAfdpvMUCslARiE4Nk=
    lastmodified: "2026-02-27T12:47:03Z"
    mac: ENC[AES256_GCM,data:lNz3mtAD7HftQDHE+2vhPLD0J1UZm5bCjUV8hbryHOaUT/qS4QMMcE+xK1yKZiccuL8oRZ/epx8cemJs+LY8zTZ9c/o3v9OAe2NwFIffu1Mt1uRxwHBxR4xUEfPSa5UDkVriVhG9j3NnfJtD6RCRH26raBTL3C2WuOnbn7H7O+U=,iv:+VH8L+m0ACjytFzG3yhrFy1LwX7kwnvPrw7UmPh7AYM=,tag:U+NpfXmtadx9mC6Nkr7rJw==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
