apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-jyvaskyla
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-jyvaskyla
data:
    http-username: ENC[AES256_GCM,data:AfxSGSnKSuM=,iv:eMRhMBcTqBT/uOAK1DN5AQMBHdd1M6LwuswqeGbAG7M=,tag:23G3dUHbenzFHeCQAxVVWQ==,type:str]
    http-password: ENC[AES256_GCM,data:1M7BJ+DJEyImtELw+F8i/Q==,iv:VI00/cWhggdAn5FfiIgQfUo3ddPn9wyBZEFTUiLRKxc=,tag:6BthKa+CfQ0mfEqn9GWiUg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-03T09:33:31Z"
          enc: CiQAhLiU4UWENm+7BzK4iWnaeFIHF07thYhsYzgbs5OvQSMYhj4SSADOezfyrtTR2ZomUMCsUgovvYnA4mQB4eG4/u5iyiPiAus+2hFZvt74UGalFq4TXq+B61zfAYIjJydPbmalZXxXn/a6Hn87bw==
    lastmodified: "2026-02-03T09:33:31Z"
    mac: ENC[AES256_GCM,data:cL2Hn1Iw28DiJsqqfjSIZrZXaMXptpWgzjW4yB0nyoH7vg56/M080jRO8ex0eZmf6Edm37DSYMPT9AdBs/fbU9FR2gFc8yFCrZCcKzkjwitlXGM1VXJmd4AbPtXCzvH3rElXTXWNe/hhyWXYkqNBj1uAe1+31jqpUvT70LhWLD8=,iv:TTUC1nCbZJAuuAIvRM6TUwLcedOGLnC+lpF1ZJirvqE=,tag:kK8yaiQC0U8vzW6vg5FFjg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
