apiVersion: v1
kind: Secret
metadata:
    name: journey-matcher
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: journey-matcher
data:
    pulsar-oauth2-key: ENC[AES256_GCM,data:sTwulkfDfEKvqyiY7Hg8aEonnwrDOVpKzJq9TxqGhwl5r/doS8KuBUbRAdr48CDW4arcIejqly0C9PwdPCrGeNo2EI1V5RT7QOEcfNG1QhpTVHxkvkz+WHN+BXjpxcdxYHU8IhPg+e94btvhwbyMuusl5mi6xo2ucrAEMjz7geUztOE7Kf+aRAWq16XAEC/Z3JGxzeZRw/NJWRww4zgZHcI92PyXcWNqLr69jQ/glgYAxCYqkdUDXV0XJAV39CfJFCVWVmG0nAter9IAsNxt8xmBByzpgqArQ19wfjD+v5Y4aRIdfhyNLXiY9gD82sOMnLFoG/b5GXmzCFU52LVkaTlPyAFDiBRfOacCP/pccWZIgJqOS9s1eTyAZm6BU/s4dEfilkrXfm2AqFKD2lYIro6EGh15dki2HedTAI6jV1W4LV6Fq+6z+il/2EO4VbDYJcJ1RCayR5HrLp0MpAVTg/wo3GbQKyic,iv:gQMciE9/gD3mhGVGeGvIL0SCG1/ZE4TQitRZPAsu4vM=,tag:jTMRrqljgBz0ETsjWW5gVA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-08-17T13:31:32Z"
          enc: CiQAUhREB9Y0328Mml/3HUwJ0wkPpJ8O/QUKTHCwxEr4KzjmMJcSSQD4ANZepEWMkyQT62a2z9IIjXFQFWoyagwNS2SzXSd1NxfqN9ZOgr08o3eJ2tKqFNs6AoS3AAJ7NCF4+LLRzKfjuxiCQmde/ng=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-17T13:31:32Z"
    mac: ENC[AES256_GCM,data:OA5Mlc1C/c9CXIa8L40rvFE3OfnNiW0KC3exxUyhTDTf64ajOsnpzP9c5i8ws+wMlkroZxYkKqIxRKTaOFFuEdalPJMW0gE+3rFAGLdjya7aiNBfrwEi1PibHmkuHa6uLasJpHBgOP5m+Sip7gwXyBAQP+5NaTWIBBzQkp+G6Oo=,iv:6/ezNPEuXgxXuvZmvK2+AXu+f4wp0u0IUheA/N6IZto=,tag:PaaB8gC1uyKltvMIqj0Ifw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
