apiVersion: v1
data:
  HEALTH_CHECK_PORT: "8080"
  HTTP_IS_HTTP2_USED: "false"
  HTTP_PASSWORD_PATH: /secrets/http-password
  HTTP_REQUEST_TIMEOUT_IN_SECONDS: "5"
  HTTP_SLEEP_DURATION_IN_SECONDS: "0.1"
  HTTP_URL: https://data.waltti.fi/jyvaskyla/api/gtfsrealtime/v1.0/feed/vehicleposition
  HTTP_USERNAME_PATH: /secrets/http-username
  PULSAR_BLOCK_IF_QUEUE_FULL: "true"
  PULSAR_COMPRESSION_TYPE: ZSTD
  PULSAR_IS_URL_IN_MESSAGE_PROPERTIES: "false"
  PULSAR_OAUTH2_AUDIENCE: urn:sn:pulsar:waltti:waltti
  PULSAR_OAUTH2_ISSUER_URL: https://auth.streamnative.cloud
  PULSAR_OAUTH2_KEY_PATH: /secrets/pulsar-oauth2-key
  PULSAR_SERVICE_URL: pulsar+ssl://pulsar.waltti.snio.cloud:6651
  PULSAR_TLS_VALIDATE_HOSTNAME: "false"
  PULSAR_TOPIC: persistent://apc-dev/source/gtfs-realtime-vp-fi-jyvaskyla
kind: ConfigMap
metadata:
  labels:
    app: http-pulsar-poller-fi-jyvaskyla-vp
    app.kubernetes.io/instance: http-pulsar-poller-fi-jyvaskyla-vp
    app.kubernetes.io/name: http-pulsar-poller
  name: http-pulsar-poller-fi-jyvaskyla-vp
  namespace: dev
---
apiVersion: v1
data:
  http-password: Zm9vCg==
  http-username: Zm9vCg==
  pulsar-oauth2-key: eyJ0eXBlIjoic25fc2VydmljZV9hY2NvdW50IiwiY2xpZW50X2lkIjoidlJMUGxhZjZsSkpwb1FZNFk2ZDdtYzVydDhTMmtqYXYiLCJjbGllbnRfc2VjcmV0IjoiZ1E1YjBCdlM2VG9xLTc4c1E3U01LS09WNGlRWnhNU043UV8zSkJWTmxQUGM1cjRWNlZfREhBOWZkYjBwRW4wdSIsImNsaWVudF9lbWFpbCI6Im1xdHQtcHVsc2FyLWZvcndhcmRlckB3YWx0dGkuYXV0aC5zdHJlYW1uYXRpdmUuY2xvdWQiLCJpc3N1ZXJfdXJsIjoiaHR0cHM6Ly9hdXRoLnN0cmVhbW5hdGl2ZS5jbG91ZC8ifQ==
kind: Secret
metadata:
  labels:
    app: http-pulsar-poller-fi-jyvaskyla-vp
    app.kubernetes.io/instance: http-pulsar-poller-fi-jyvaskyla-vp
  name: http-pulsar-poller-fi-jyvaskyla-vp
  namespace: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-pulsar-poller-fi-jyvaskyla-vp
    app.kubernetes.io/instance: http-pulsar-poller-fi-jyvaskyla-vp
    app.kubernetes.io/name: http-pulsar-poller
  name: http-pulsar-poller-fi-jyvaskyla-vp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-pulsar-poller-fi-jyvaskyla-vp
      app.kubernetes.io/instance: http-pulsar-poller-fi-jyvaskyla-vp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: http-pulsar-poller-fi-jyvaskyla-vp
        app.kubernetes.io/instance: http-pulsar-poller-fi-jyvaskyla-vp
        networkPolicy: client-only
        podDisruptionBudget: max-unavailable-one
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: http-pulsar-poller-fi-jyvaskyla-vp
        image: tvvlmj/http-pulsar-poller:sha-8c3e3d89128ee4976714117a2fe3f9e904f6132e
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: liveness-port
          periodSeconds: 10
        name: http-pulsar-poller-fi
        ports:
        - containerPort: 8080
          name: liveness-port
        resources:
          limits:
            cpu: "1"
            ephemeral-storage: 2Mi
            memory: 512Mi
          requests:
            cpu: 251m
            ephemeral-storage: 8Ki
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 10001
          runAsUser: 10001
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz
            port: liveness-port
          periodSeconds: 2
        volumeMounts:
        - mountPath: /secrets
          name: http-pulsar-poller-fi
          readOnly: true
      volumes:
      - name: http-pulsar-poller-fi
        secret:
          secretName: http-pulsar-poller-fi-jyvaskyla-vp
