apiVersion: v1
kind: ConfigMap
metadata:
  name: journey-matcher
data:
  # Optional
  APC_WAIT_IN_SECONDS: "6"
  COUNTING_SYSTEM_MAP: >-
    [
      ["DL-Mccl1",["fi:kuopio:44517_6","Deal Comp"]],
      ["emblica-sc01-apc-device1",["fi:kuopio:44517_160","Emblica"]],
      ["emblica-sc02-apc-device1",["fi:kuopio:44517_6","Emblica"]],
      ["emblica-sc03-apc-device1",["fi:jyvaskyla:6714_521","Emblica"]],
      ["emblica-sc04-apc-device1",["fi:jyvaskyla:6714_518","Emblica"]],
      ["JL518-APC",["fi:jyvaskyla:6714_518","Telia"]],
      ["JL521-APC",["fi:jyvaskyla:6714_521","Telia"]],
      ["KL006-APC",["fi:kuopio:44517_6","Telia"]],
      ["KL160-APC",["fi:kuopio:44517_160","Telia"]]
    ]
  # FEED_MAP: "TO_BE_FILLED_IN_OVERLAY"
  # Optional
  HEALTH_CHECK_PORT: "8080"
  PINO_LOG_LEVEL: "info"
  # PULSAR_APC_CONSUMER_TOPICS_PATTERN: "TO_BE_FILLED_IN_OVERLAY"
  PULSAR_APC_SUBSCRIPTION: "journey-matcher-apc-sub"
  # Optional
  PULSAR_BLOCK_IF_QUEUE_FULL: "true"
  # Optional
  PULSAR_COMPRESSION_TYPE: "ZSTD"
  # PULSAR_GTFSRT_CONSUMER_TOPICS_PATTERN: "TO_BE_FILLED_IN_OVERLAY"
  PULSAR_GTFSRT_SUBSCRIPTION: "journey-matcher-gtfsrt-sub"
  PULSAR_OAUTH2_AUDIENCE: "urn:sn:pulsar:waltti:alpha"
  PULSAR_OAUTH2_ISSUER_URL: "https://auth.streamnative.cloud"
  PULSAR_OAUTH2_KEY_PATH: "/secrets/pulsar-oauth2-key"
  # PULSAR_PRODUCER_TOPIC: "TO_BE_FILLED_IN_OVERLAY"
  PULSAR_SERVICE_URL: "pulsar+ssl://sandbox.waltti.snio.cloud:6651"
  # Optional
  PULSAR_TLS_VALIDATE_HOSTNAME: "false"