apiVersion: apps/v1
kind: Deployment
metadata:
  name: journey-matcher
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: journey-matcher
  template:
    metadata:
      labels:
        app: journey-matcher
        networkPolicy: client-only
        podDisruptionBudget: max-unavailable-one
        app.kubernetes.io/name: journey-matcher
    spec:
      containers:
        - name: journey-matcher
          image: tvvlmj/waltti-apc-journey-matcher:edge
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 100Mi
          envFrom:
            - configMapRef:
                name: journey-matcher
          ports:
            - name: liveness-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: liveness-port
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: liveness-port
            timeoutSeconds: 5
            failureThreshold: 90
            periodSeconds: 2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
      volumes:
        - name: journey-matcher-secret-volume
          secret:
            secretName: journey-matcher
