apiVersion: v1
kind: Secret
metadata:
    name: http-pulsar-poller-fi-kuopio-vp
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: http-pulsar-poller-fi-kuopio-vp
data:
    http-username: ENC[AES256_GCM,data:r0oh4IoLQKbyL89LL8oc0h4krq+HHGxTohCiDMiSaqa+HmipG04q1Z2sc9UhHDTyoYMsgW0VT7PBKFJRgEt9kgInFuQAuoFrMbRWibAvi70echSgJY1s/7Wcp78rrAlOxr7k9S3gbwEElQh60SAClVoiasOb2g0=,iv:STtJZEF2I5ZTT1hqFnZrmWMCuCuDbnD+ENRKXBVGmjI=,tag:8RbfGh7zbfQ3wMT144df4w==,type:str]
    http-password: ENC[AES256_GCM,data:fmnA05uckaXJwwCJqI6MOK2ngp5E5ei0Efi9HUdUC8IeHdRqo0Z9fFxOIs+89xDbn3+ag30fnOz23RirVdQEbQn6H/j3jC6i0568FIXdSoeKyC+MFBLFT+DQSWfO0LIHQY5MbLadSldeig0f+shP69yF4mibcvk=,iv:nyuJIPli8ohqVuLWkagrsQSSSuVGWUscMhtuG0PBjyA=,tag:K/0KnbV+SKDwM1/laofv2A==,type:str]
    pulsar-oauth2-key: ENC[AES256_GCM,data:x8AjKDQXtS9V5RgCPB5yW3FI19XXSbh4jUVWKItfx35JSU/d0oyZZD1Mq9MuddIGS4Eq61+yupN9k+Mn8HXQgDf7ZbutwxSnAtj4lAJju0XXHUFp9a/H69OBWf1FZuQREz82qS+cg7Du99K1QYwibG6hvlXdCRejtOPcpjf8QcpEDL6mHVCZfrB1VHAtLDHFB2aNSr1nEb/nxfoCoGIRM8HE0T2BFNvPsakLnpZBwLv3EzJb126TeuEUlFGpE5luUZjVKlOvYeyexO5L5yXX6pwGU7lWy8aBoKVOi8SSNu519CwIotUR8rFsdfFj51s/rcD8nTI33SeifPZzr1SbGLt0cm2lQ1Bzf26VZukKorIJiJHyy9LWjwRSLmZFWTgwHrwX0gk5Q9XpE0oAnPRa+YbQaStmLVaeLzLDoRhisNrFe5/gDM3x9Mgo0KSFFZRvIVztmdkxRzVqbDcPeDJukzfp+Fn7YkUR2/14YjDDf3eShVs6fOyhOJv7IS7G26xfs47wDtIP6fzQyVZcT7GwKY/xeOhwXsPlDOlxltSiFtIObwlk19DRrW8MXfHfoYglNwImSFH3u8QT9i2jhjVgdonx8LKfe3vy0CF4UccoMemyAqyHDn6D09zU6oZSjqAA8P+TzKrN7A9mo2NZHDSlzBMqkoz6cA6QBNrGqlmqpYVmDUPmEaawEtMtuX+MawiAdT0BKGnwBXKQOw+hUF1FGpqMd1r4pqs/dMD41REV81+6nmQ+gv061kBTGGMeaOKRCS34Fu0z8Gh/PrxKwlbwJ+Wn9CNP4wWsIyLg,iv:36Uqfv4SWh2AEgrJHYJjasVZx4ALgWcIGWHXispQvCg=,tag:TVPEVsOjOx2cXhXw3MdX0Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-06-16T05:56:25Z"
          enc: CiQAUhREB3gnnvi7UypvhWKTpkvkRoX/2Ni4j/KZCpI+MP0UbhUSSQD4ANZeEPKilj+b5VtD8Qy2SZWOdQ5s/imSJSoNic0O8k3DYTIq2q9sllcrkwtboH5ntVJfTb0Wzed5UFEbK5eCeJ1g6nZCuaI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-16T05:56:25Z"
    mac: ENC[AES256_GCM,data:bc07wIXwM6NzKdJL4K+TawWrEqX3uWvJbOmQsZ1/WjJGlwcS3gXRdxP0mjRqRioHnlLcb1wV5eI3LFa6XvK5QnVFxCDoR7etYesw4Se5+kttT2dk6CGwzsS3kURemgH8lPB/anyqUih8g1/6b2KznVJqDFRtrq0ylJLv7HG67KQ=,iv:5AI35387ZVE2e+RRt+Clqoq+IYIoxFXDEzvMw+qEYZM=,tag:1wRRymqkGhVun8n2pMt/7A==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
