apiVersion: v1
kind: Secret
metadata:
    name: journey-matcher-secret
    labels:
        app.kubernetes.io/name: journey-matcher
data:
    pulsar-oauth2-key: ENC[AES256_GCM,data:dneE14jEwJ5TSAyRXhyHD1ii+BpzqxzM5jxKU8xwmsrEs30iqIofWpgjTKpn2coEYoHgDy4xT069z9yqOVLzyFo0oJ44Cy9sSDlW/KvTDMClxmqgkb/6oQp8f5BhlELaHiIAyMcq3EbG7A+E6oBrd1dCTgs6l9gVmz2YBjdb955Ts8bvtq79lMo2LJUCu2vktMSJcCFSbnbvVznfUSQSULEiIpIuk3IgWZ5TQvar0M2n7Hr9ba3BRHbxuTau+KGMaf683tnaclLt262YnVNbtzKRoeYMIFjm5qnbNuFHOjzuFlGWADU3n1yhjnGTyfj839e2h98SpLJOiB1bi/C/Aqo55Ttwth9Ntv0o5mmzZVHc/zQ+3KFTJN3q9Y7ciJm3srB8XHyLn3qcrb8SmFTVyyGld0QesbeDaKOzR4nYrBcIJTR3Hd/fgs8ARtnnHybCwUJGEhtDpfkMenVMcNfvF5jpNZDhriTy,iv:s8NVXF9IgZH7CCzMzqQqYdpEFC8ORS7ZGRxSn7KW+Ro=,tag:Y8J/UnegG/2+8sY1CD2WwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18np9hgxyze042dksv234u34p9lxyy7cx4dqkyj27470c64any5fqu6kd6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMW0rblBwVUo1V2xUaWFv
            UXFVaWFISi92RWtSNms0UjFKYWNaWWtSc3hjCmRmejNmWWVRalFENDV0QjNWTi9h
            bkdBWkFKZnhwdW1sYkxZZXVwUzJTbncKLS0tIGlHbmZhU2xjOWdaeUliRHN5M0wz
            Q05wTjYzaUdmNEpyWHBNRXEzQ05hekEKtZLZ6WK4HK9AptUP6vI23tnBGEjLOX2b
            YBw1bFeg2GEre2Y3FOvkd/X4Okmuz5AlsLZYLpz9bELr4v1kZ7y6DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-29T23:24:17Z"
    mac: ENC[AES256_GCM,data:vJX5debAAUfeJXBKOyDdDmScUfsUtIgIlOyXNmvyeMmJHURsH1ct/koIQM1xIktkT1M94eg9faHy100AV1H4tVAf2Ayfh7/t5rwLo7SSZ35mhMSh2+AS5go7PEqC6vcgoh/X56xkEZzulBDJXlDU/vMcQ7VCxZDoiMhntufKp5U=,iv:d/2R69RyiFdEYByDLqdsI+tvgUi9i7tcfXmHVHuYjVI=,tag:gDSKMHzfRn2Gig/mAzy/yQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
