namespace: dev
resources:
  - ../../base

configMapGenerator:
  - name: mqtt-pulsar-forwarder
    behavior: merge
    literals:
      - "MQTT_URL=mqtts://mqtts-dev.apc.waltti.fi"
      - "MQTT_CLIENT_ID_PREFIX=mqtt-pulsar-forwarder-dev"
      - "PINO_LOG_LEVEL=debug"
      - "PULSAR_TOPIC=persistent://apc-sandbox/source/mqtt-apc-from-vehicle"
      # - "PULSAR_OAUTH2_AUDIENCE=urn:sn:pulsar:waltti:alpha"
      - "PULSAR_SERVICE_URL=pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"

patches:
  - path: history-limit.yaml

generators:
  - ./ksops-secret-generator.yaml
