namespace: dev
#namePrefix: dev-
resources:
  - ../../base
  - namespace.yaml

configMapGenerator:
  - name: mqtt-pulsar-forwarder
    behavior: merge
    literals:
      - "MQTT_URL=mqtts://dev.mqtt.apc.lmj.fi"
      - "PULSAR_TOPIC=persistent://apc-sandbox/source/mqtt-apc-from-vehicle"
generators:
  - ./ksops-secret-generator.yaml