apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-lahti
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-lahti
data:
    http-username: ENC[AES256_GCM,data:uT5GSL0XDhg=,iv:2aXLqII1YG8J91U/mJiFCp9FfpAVgiyJTcKQI7P1FH0=,tag:av89LgMRaZYlMeJXrX+xdg==,type:str]
    http-password: ENC[AES256_GCM,data:zfhoCiynFV6wPZqK+7xQMw==,iv:EBVWLlKSApgaODlhQ4ipCWxhsty3Mj4TiAEwWGGFC98=,tag:xmIds7L0LKTpY/HXeHlmwg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-05-22T07:24:26Z"
          enc: CiQAQ7huFqySykX8oF39ahqpqR4Iq0K6LN8lJyxJ2eII0Yx9ot8SSQC//Ayi1p5t0o2K8xildRaveIO88yirOlDwKuvrz7dLYLfKqLQbDwUJVsHev8QHyynfuCrIL5eZn+0QItZDwQXQQRjYLxNpGyo=
    lastmodified: "2026-05-22T07:36:55Z"
    mac: ENC[AES256_GCM,data:aWaAcIbDzpi30yD0OkipRTbjF/ZfiODJKVS5hXLL6OyL5s1K6Zgi+fcVk7bg1s41kwJwmgDGtZHn1ZrKq6c7dHbg33Q/tx7VYRhhr44qhR/vUeTpIJVfZa4ldvFY3wQmeakqF5bcsxvuSDq8VkVpBDlJX9IIPMusoswbnAuQvb0=,iv:dbFdYPvr9Vt9YFm+ALxhwyDjhFiNxzDxxu73FszcrUU=,tag:IAYIj1hKO5NKCNUXs9uQFQ==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
