apiVersion: v1
kind: Secret
metadata:
    name: mqtt-mqtt-duplicator
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: mqtt-mqtt-duplicator
type: Opaque
data:
    SOURCE_MQTT_USERNAME_PATH: ENC[AES256_GCM,data:XhAslOl6IErAn0CxbQPjHg==,iv:tU/MSLfyUOHzn27q1HaPxka59FccLxtAchI/yTuBWYY=,tag:0kYVDd1x3SOzV+7Vu6mM2w==,type:str]
    SOURCE_MQTT_PASSWORD_PATH: ENC[AES256_GCM,data:D9xcf26E9QNOxusKSJTYpKE3EzxEN6AJhCL34UkMOaBZlSlaVkHBCUz4V6Cil6phlv+VLPLQWIVD9Ug8,iv:4O3JGIbPbZaNlSKF313ZPQCy2S7dzjcgGZkT0DCc/7w=,tag:W5Rhpfbc5ul4JvAMVhWVxw==,type:str]
    DEST_MQTT_USERNAME_PATH: ENC[AES256_GCM,data:Dh+vV1TFyOAw1jWUSXh28A==,iv:VzgUnj5c5b2Emk5U7Xwm6UfylirI4VzT9tanknIzSOg=,tag:26696xXPfWIUtHOjZpHUdg==,type:str]
    DEST_MQTT_PASSWORD_PATH: ENC[AES256_GCM,data:6LinqXQlUmsGnsbalpBP2zRn7WJLQmWj5UqkppSWUOxY/jZCppO1eRe8Y71CwtgDrTNlq5ZtFePOcwNpdUmdTjh8eSpxbh0jYgHIEztTAvpQ905BslouwA==,iv:jIIPjcXYdo779Qzx1SNWRFTS/jJnDnbvfI/MJ2l2SDM=,tag:X78m+Q22eB1DFYk0j10f1A==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-05T12:56:01Z"
          enc: CiQAQ7huFrsuKADZTskk6ekj1eUagWWth8phucmOohA4pFcDqX0SSQC//AyiJirHf91/F7WMZlXP07LEg1oaFSjxSMSJNskevKEXRyc4VXYWZva97viJiQgidEZGkA39DAQHeGBAWmyo5eDUeoJyyRQ=
    lastmodified: "2026-02-05T12:56:01Z"
    mac: ENC[AES256_GCM,data:agn7RvZSg5AmeA8PUKrJ9dWoQphjkLik7QnWV5tbIDCdCpWJSP6mG0qLU9ln4PaXAQ1el6ny8FBwolyMK4neKHZPf5ZgT05g0X8A8Tstk+DLGLAYFlIUot/b2OOw1F7X6ktdk9wscxdwp6WaN78QclhDtyp6/rVLDktI0V8b6qo=,iv:1KzQDuxz0uJomoFRA8EvlZHiWIzadqxZ1WqhbeNr6fg=,tag:H4BJ/GF+FfpzohPzNyp1Hg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
