apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-mqtt-forwarder
spec:
  template:
    spec:
      containers:
        - name: pulsar-mqtt-forwarder
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
              ephemeral-storage: 100Mi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 100Mi
