apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-mqtt-forwarder
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pulsar-mqtt-forwarder
  template:
    metadata:
      labels:
        app: pulsar-mqtt-forwarder
        app.kubernetes.io/name: pulsar-mqtt-forwarder
        networkPolicy: client-only
        podDisruptionBudget: max-unavailable-one
    spec:
      containers:
        - name: pulsar-mqtt-forwarder
          image: tvvlmj/pulsar-mqtt-forwarder:edge
          imagePullPolicy: Always
          resources:
            # Autopilot only considers requests
            # GCP Autopilot does not accept less on 2023-04-20.
            # Check docs at https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests
            requests:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 100Mi
          envFrom:
            - configMapRef:
                name: pulsar-mqtt-forwarder
          volumeMounts:
            - name: pulsar-mqtt-forwarder-secret-volume
              mountPath: "/secrets"
              readOnly: true
          ports:
            - name: liveness-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: liveness-port
            failureThreshold: 30
            periodSeconds: 2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsGroup: 10001
      volumes:
        - name: pulsar-mqtt-forwarder-secret-volume
          secret:
            secretName: pulsar-mqtt-forwarder
