resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: pulsar-mqtt-forwarder

configMapGenerator:
  - name: pulsar-mqtt-forwarder
    literals:
    - MQTT_PASSWORD_PATH=/secrets/mqtt-password
    - MQTT_USERNAME_PATH=/secrets/mqtt-username
    - PINO_LOG_LEVEL=info
    - PULSAR_OAUTH2_KEY_PATH=/secrets/pulsar-oauth2-key

