resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: vehicle-position-splitter

secretGenerator:
  - name: vehicle-position-splitter
    literals:
    - pulsar-oauth2-key=whatever
    options:
      disableNameSuffixHash: true

configMapGenerator:
  - name: vehicle-position-splitter
    literals:
      - APC_WAIT_IN_SECONDS=6
      - HEALTH_CHECK_PORT=8080
      - PULSAR_APC_SUBSCRIPTION=vehicle-positon-splitter-vr-sub
      - PULSAR_BLOCK_IF_QUEUE_FULL=true
      - PULSAR_COMPRESSION_TYPE=ZSTD
      - PULSAR_GTFSRT_SUBSCRIPTION=vehicle-position-splitter-kuopio-sub
      - PULSAR_OAUTH2_ISSUER_URL=https://auth.streamnative.cloud
      - PULSAR_OAUTH2_KEY_PATH=/secrets/pulsar-oauth2-key
      - PULSAR_TLS_VALIDATE_HOSTNAME=true
