resources:
  - deployment.yaml

configMapGenerator:
  - name: vehicle-position-splitter
    literals:
      - HEALTH_CHECK_PORT=8080
      - PULSAR_BLOCK_IF_QUEUE_FULL=true
      - PULSAR_COMPRESSION_TYPE=ZSTD
      # - PULSAR_OAUTH2_ISSUER_URL=https://auth.streamnative.cloud
      # - PULSAR_OAUTH2_KEY_PATH=/secrets/pulsar-oauth2-key
      - PULSAR_TLS_VALIDATE_HOSTNAME=true
