apiVersion: v1
kind: Secret
metadata:
    name: mqtt-mqtt-duplicator
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/name: mqtt-mqtt-duplicator
type: Opaque
data:
    SOURCE_MQTT_USERNAME_PATH: ENC[AES256_GCM,data:3uPK/CcY4hftGClySh+byw==,iv:W+jBkpZFfe5hwtEuO9S7hZQUeEpTOj257di9LYa4AWs=,tag:Z7X6/+sJ6vw1mgvWuDJO6A==,type:str]
    SOURCE_MQTT_PASSWORD_PATH: ENC[AES256_GCM,data:qmd9w/7XZE95UcF1CB4AqXNgRJqBCbBEkELF3UYicGP6fr439U7DOB70cRMNhqq11FHIwcFR54/c0Xh5,iv:daAI6ETVq5VM+HFwZZAKaw2RtiH5zA5panCdXlFJ8mk=,tag:fUd8g00t2u9ucAjDA6tIbQ==,type:str]
    DEST_MQTT_USERNAME_PATH: ENC[AES256_GCM,data:EfXhLGFrO2WQEdovFQ68pg==,iv:vXVu4a5WVs/FWDDYHatohaZXAz544wl7vRSXQ0SssCc=,tag:vYLgiE2xcrY8UMGt1pF93Q==,type:str]
    DEST_MQTT_PASSWORD_PATH: ENC[AES256_GCM,data:FRsr3PKgjU6MY0ZOaROT5USWrZOaHVxI5zBpTHOwFSt0j3blwkf00g/h/SFrPysgAGgZMuQHupXZT4QeSr7mRRjQIhsOzrA+VoYEykOcKoSUuf7ltt8ELw==,iv:w0PRXyRjxuI8OdXWXU3Pl1XskOipc9HSH6byR4HkOfc=,tag:1IRFAAENT+d6QKD5FSKZLw==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-05T11:58:46Z"
          enc: CiQAQ7huFurvD7VeuMEcI3uSKF8WN94msggMyhys5aTUiT2u1qQSSQC//AyiQWT0fgW+cXsHMPsqfMxrl5fCIuetoB6e/8yN45IV4hFgCX/azwo0ef4xLFk3E+gRnlFJSTy+cBp3h9lncdMv7dCM4ZU=
    lastmodified: "2026-02-05T11:58:46Z"
    mac: ENC[AES256_GCM,data:2We7tYvFSfRZImM3uf6YTbVdHtjhQwW5KurhHlZVM6P4j+hBhskhU2KT3M5dVpkAIluIvkORYnVfl/rwWqmmkkc5W1v5O52tI/ci8hqOzYBxQXwX8q/GXCNCBDz2B9LxuyOvlROHWfNwKsVmIQXRANpsDwonBNxA7bvBtWyyKtA=,iv:63BCutjQXgCv1+KZNnj3rJFvkICrN3NOxlQTjgx3idY=,tag:JBvA+/4nWeZXZJsnoRbheA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
