apiVersion: v1
kind: Secret
metadata:
    name: gtfsrt-vp-poller-fi-lahti
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: gtfsrt-vp-poller-fi-lahti
data:
    http-username: ENC[AES256_GCM,data:+QmFbgBjFIs=,iv:PBcQxc4RsqJ2LqcJ5AQU4JD9aNjlrord01I2uT+9QRI=,tag:jzpDh+exJh04L5PlLgHgRw==,type:str]
    http-password: ENC[AES256_GCM,data:9Rmf3NvTZ+1qcT7n,iv:gcOairda29oWTlJbocPSGquWgYmAMHipqZYJ5fuxvhI=,tag:GElnS24N4kQohlvTOp2ZKQ==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-05-22T07:24:29Z"
          enc: CiQAhLiU4R3MiR/x5m7bTSZpe9XAOf+FXkU6H65s94w1PtXL3MISSQDOezfyKRAQ4TRuEcNSP8zXw2gj38OTmIPyWZ/FyPjvOqhMppVIOW9zS9HXZwoZXHY1CWZZtid9yN7FZ3hM5W83W5BayDTY5eE=
    lastmodified: "2026-05-22T07:24:29Z"
    mac: ENC[AES256_GCM,data:F7aGLATaAyHIvA5mzy+x5WMcln/xZZg0w6sMcw5x4/n/fyi5+sK2dEonr/3mw32mbtUCBTIu5YytdwnGXW22z7snAadiklmcRMYLeXYjiH8MquwjEA3IhPkuuqKkVroH3xDD1zV0s9A3NsI6woH7rH19MWkjaNnqNw4zs0xMrPU=,iv:izPgQTTaHYsHcseyqUSHjVltU+Ea2mjT7BV7EQp9vQs=,tag:TDxSvfc5p5H4a7+8eOxNHQ==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
