resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: mqtt-deduplicator

configMapGenerator:
  - name: mqtt-deduplicator
    literals:
    # Optional
    - "DEDUPLICATION_WINDOW_IN_SECONDS=3600"
    # Optional
    - "HEALTH_CHECK_PORT=8080"
    # Optional
    - "PULSAR_BLOCK_IF_QUEUE_FULL=true"
    # Optional
    - "PULSAR_COMPRESSION_TYPE=ZSTD"
    # PULSAR_CONSUMER_TOPICS_PATTERN: "TO_BE_FILLED_IN_OVERLAY"
    - "PULSAR_OAUTH2_ISSUER_URL=https://auth.streamnative.cloud"
    - "PULSAR_OAUTH2_KEY_PATH=/secrets/pulsar-oauth2-key"
    # PULSAR_PRODUCER_TOPIC: "TO_BE_FILLED_IN_OVERLAY"
    - "PULSAR_SUBSCRIPTION=mqtt-deduplicator-sub"
    # Optional
    - "PULSAR_TLS_VALIDATE_HOSTNAME=false"

secretGenerator:
  - name: mqtt-deduplicator
    literals:
    - mqtt-username=foo
    - mqtt-password=bar
    - pulsar-oauth2-key=whatever
    options:
      disableNameSuffixHash: true

