---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Shared
  - client-only-network-policy.yaml
  - max-unavailable-one-pdb.yaml
  - analytics-db-sa.yaml
  # Apps
  - analytics-db-sink.yaml
  - http-pulsar-poller-fi-jyvaskyla-vp.yaml
  - http-pulsar-poller-fi-kuopio-vp.yaml
  - journey-matcher.yaml
  - mqtt-deduplicator.yaml
  - mqtt-pulsar-forwarder.yaml
