---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Shared
  - client-only-network-policy.yaml
  - max-unavailable-one-pdb.yaml
  # Services
  - analytics-db-schema-migrator.yaml
  - mqtt-pulsar-forwarder.yaml
