apiVersion: v1
kind: Secret
metadata:
    name: vehicle-registry-poller-fi-kuopio
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: vehicle-registry-poller-fi-kuopio
data:
    http-username: ENC[AES256_GCM,data:06BO5NZpv1s=,iv:FYn/IG4GEKsbKHKW1yqQbZsfV5AvoIkKctZWGJ5K/bs=,tag:paa2l+ZnAgack7wwnup0yg==,type:str]
    http-password: ENC[AES256_GCM,data:N3RrMc5dvwKEy1uDThHGQw==,iv:XkkRomooki9ZJ8/A8Uh66l3C6/Bfew+pia/T8IBxLiI=,tag:/iJNgVMMJAFKt97BMt5j9Q==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:24:40Z"
          enc: CiQAUhREBy7w8o90FpjoXfE4LQeskjEyVJVmMGkwTZ4QyaShAB4SSQD4ANZeCk6AAZrffuSj130nwrR98P9sOF9nkpJXhtJkvUfUdIkhSUuwO5IjsCbfNUMhP7SKFy9Ruyap0IiQqYBD/Y7HJxOpYvs=
    lastmodified: "2026-05-22T07:22:26Z"
    mac: ENC[AES256_GCM,data:qJviEVm5SkvdyoeODfQ9LMz+V+cijGmjGrBsjGul0e3GCRwRn+HIs0o4GSDxCx6ncShbrD/qtoPdmtgF9WxpWBQ3epFd/tKU+d7XywMLxvm6xVUJEUMrg4msMgeXxOX3MLqHSRg8TzXh6hQ7SHl7BMV4mn0L3gaI51E1SqnNCZw=,iv:gWXBH6ky/Gc0zhi4n4Df78C4D+Bf9OQuI6G1Re/C9fE=,tag:Nl/b0/M0UCCz3TbZE+9LHA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.7.3
