apiVersion: batch/v1
kind: CronJob
metadata:
  name: profiler
spec:
  schedule: "5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: profiler
            image: tvvlmj/waltti-apc-vehicle-anonymization-profiler:edge
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 4
                memory: 16Gi
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            envFrom:
              - configMapRef:
                  name: profiler
            ports:
              - name: liveness-port
                containerPort: 8080
            livenessProbe:
              httpGet:
                path: /healthz
                port: liveness-port
              failureThreshold: 1
              periodSeconds: 10
            startupProbe:
              httpGet:
                path: /healthz
                port: liveness-port
              failureThreshold: 30
              periodSeconds: 2
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 10001
              runAsGroup: 10001