apiVersion: v1
kind: Secret
metadata:
    name: gtfsrt-vp-poller-fi-kuopio
    annotations:
        kustomize.config.k8s.io/behavior: replace
    labels:
        app.kubernetes.io/instance: gtfsrt-vp-poller-fi-kuopio
data:
    http-password: ENC[AES256_GCM,data:qd7Bio8/zdCAxBL0,iv:YylCXFOfOhNDATvsMHR0eyaBr/p9nvXildCfIj6DFIs=,tag:BX7YNHjunY+UPmtEoCjxVQ==,type:str]
    http-username: ENC[AES256_GCM,data:yOld8x1tsoc=,iv:no6M4YXfn2uK2hghuw79CSeaUba98jfO5zIDeDTtbbo=,tag:tOYxGL9vz2ODAJJjdMUMfg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-27T12:11:14Z"
          enc: CiQAQ7huFgUqHw8zLTozT4agHWfeoNUfevSMvY6wKikGmI3ei2kSSQC//AyiiFeuVj9ObElm6ei2ivd9hnnYmOMU4iHSNR92oN+tpVkfR/2bHv9Dxmsq/kt5Fzfn/8hdbwQaVyivY6nLv8xbVkzh5pM=
    lastmodified: "2026-05-22T07:22:25Z"
    mac: ENC[AES256_GCM,data:WzIYXptux2Qj3a1WVP7psU4nYl3Y8OP/+rWCq8mwQaI5MggkzVFiCkNxzITBJfCCzWp5mfPEG6TO8DmxuMtRyq/6OI2PVuMnfrKUI+vSSX3c5lxdBPjVmI7jIFqvKywBA5ErNDxJhYJxUAJTobnP3yro41vMEFUpBjiOimsbE7o=,iv:0bYH7RaPSh70ugwFkH7PP43HTQzS6wovVljV1Sfn2/o=,tag:EP9HuIBSnGTktCVrrMPRlg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.7.3
