namespace: dev
resources:
  - ../../base

configMapGenerator:
  - name: gtfsrt-vp-poller-fi-kuopio
    behavior: merge
    literals:
      - "HTTP_PASSWORD_PATH=/secrets/http-password"
      - "HTTP_URL=https://opendatavilkku.mattersoft.fi/rtapi/gtfsrealtime/v1.0/feed/vehicleposition"
      - "HTTP_USERNAME_PATH=/secrets/http-username"
      - "PINO_LOG_LEVEL=debug"
      - "PULSAR_TOPIC=persistent://apc-sandbox/source/gtfsrt-vp-fi-kuopio"
      # - "PULSAR_OAUTH2_AUDIENCE=urn:sn:pulsar:waltti:alpha"
      - "PULSAR_SERVICE_URL=pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"
patches:
  - path: history-limit.yaml

generators:
  - ./ksops-secret-generator.yaml