namespace: staging
resources:
  - ../../base

configMapGenerator:
  - name: pulsar-mqtt-forwarder
    behavior: merge
    literals:
      - "MQTT_URL=mqtts://mqtt-staging.apc.waltti.fi"
      - "MQTT_TOPIC=apc/v1/authority-id/"  # Rely on topicSuffix property
      - "PULSAR_TOPICS_PATTERN=persistent://apc-staging/aggregated/aggregated-apc-journey"
      - "PINO_LOG_LEVEL=info"
      - "PULSAR_SUBSCRIPTION=pulsar-mqtt-forwarder"
      - "PULSAR_OAUTH2_AUDIENCE=urn:sn:pulsar:waltti:beta"
      - "PULSAR_OAUTH2_ISSUER_URL=https://auth.streamnative.cloud"
      - "PULSAR_SERVICE_URL=pulsar+ssl://staging.waltti.snio.cloud:6651"
      
patches:
  - path: history-limit.yaml

generators:
  - ./ksops-secret-generator.yaml