apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-message-inspector
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mqtt-message-inspector
  template:
    metadata:
      labels:
        app: mqtt-message-inspector
        networkPolicy: client-only
        podDisruptionBudget: max-unavailable-one
        app.kubernetes.io/name: mqtt-message-inspector
        app.kubernetes.io/instance: mqtt-message-inspector
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: mqtt-message-inspector
          image: tvvlmj/waltti-apc-mqtt-message-inspector:edge
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 1Gi
          envFrom:
            - configMapRef:
                name: mqtt-message-inspector
          env:
            - name: HTTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mqtt-message-inspector
                  key: http-username
            - name: HTTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt-message-inspector
                  key: http-password
          volumeMounts:
            - name: mqtt-message-inspector-secret-volume
              mountPath: "/secrets"
              readOnly: true
            - name: mqtt-message-inspector-data-volume
              mountPath: "/data"
          ports:
            - name: liveness-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: liveness-port
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: liveness-port
            timeoutSeconds: 5
            failureThreshold: 90
            periodSeconds: 2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
      volumes:
        - name: mqtt-message-inspector-secret-volume
          secret:
            secretName: mqtt-message-inspector
        - name: mqtt-message-inspector-data-volume
          emptyDir: {}
